version: '3.8'

services:
  backend:
    image: remosa-backend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    # volumes: # Удаляем монтирование кода для продакшена
    #   - ./backend/alembic:/app/alembic # Оставляем для миграций, если нужно
    depends_on:
      - redis

  frontend:
    image: remosa-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    # volumes: # Удаляем монтирование кода и node_modules для продакшена
    #   - ./front_new:/app
    #   - frontend_node_modules:/app/node_modules
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      VITE_API_URL: ${VITE_API_URL}
      GENERATE_SOURCEMAP: "false"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend

volumes:
  redis_data:
  # backend_code: # Удаляем volume для backend_code
  # frontend_node_modules: # Удаляем volume для frontend_node_modules 