version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # Только для разработки
      - ./backend/alembic:/app/alembic  # Для миграций
    depends_on:
      - redis

  frontend:
    build: 
      context: ./front_new
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./front_new:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://192.168.1.122:8000
      GENERATE_SOURCEMAP: "false"
    env_file:
      - ./front_new/.env
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6.2-alpine  # более легковесный образ
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.21-alpine  # более легковесный образ
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./nginx/logs:/var/log/nginx  # логи nginx
    depends_on:
      - backend
      - frontend

volumes:
  redis_data:
  backend_code: