version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://remosa:1234567890@192.168.1.178:5432/remosa
      - SMS_GATEWAY_URL=${SMS_GATEWAY_URL}
      - SMS_GATEWAY_API_KEY=${SMS_GATEWAY_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

volumes:
  redis_data:
  frontend_node_modules: 