"""Make device_id nullable in logs table

Revision ID:012
Revises: 011
Create Date: 2024-06-01 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012'
down_revision = '011' # !!! ЗАМЕНИТЕ ЭТО ЗНАЧЕНИЕ !!!
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ### 