from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017'
down_revision = '016'  # Пожалуйста, проверьте это значение в вашей последней миграции
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('alert_sms_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_devices_alert_sms_template_id_command_templates'),
        'devices', 'command_templates',
        ['alert_sms_template_id'], ['id']
    )
    op.add_column('devices', sa.Column('send_alert_sms', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'send_alert_sms')
    op.drop_constraint(
        op.f('fk_devices_alert_sms_template_id_command_templates'),
        'devices', type_='foreignkey'
    )
    op.drop_column('devices', 'alert_sms_template_id')
    # ### end Alembic commands ### 