"""add platform_id and device_id to audit_logs

Revision ID: 574dcb0df075
Revises: 587cab78bf8f
Create Date: 2025-07-03 15:10:39.182855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574dcb0df075'
down_revision: Union[str, None] = '587cab78bf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
