"""add platform_id and device_id to audit_logs

Revision ID: 5b4ae26c26f5
Revises: 574dcb0df075
Create Date: 2025-07-03 15:51:24.050248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4ae26c26f5'
down_revision: Union[str, None] = '574dcb0df075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'device_id')
    op.drop_column('audit_logs', 'platform_id')
    # ### end Alembic commands ###
