"""Add notifications table

Revision ID: 5e61b1fa7fa2
Revises: d36ec4a30673
Create Date: 2025-07-04 17:55:52.182682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e61b1fa7fa2'
down_revision: Union[str, None] = 'd36ec4a30673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
