"""platforms, platform_users, audit_logs, связь устройств с платформой

Revision ID: 61f3f8c0e66c
Revises: 24276f29880d
Create Date: 2025-06-30 13:23:25.112120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f3f8c0e66c'
down_revision: Union[str, None] = '24276f29880d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
