"""Add Prometheus monitoring fields to Job and JobExecution models

Revision ID: a8c809f0031f
Revises: 027c9b714761
Create Date: 2025-07-05 20:11:24.871326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c809f0031f'
down_revision: Union[str, None] = '027c9b714761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('prometheus_value', sa.String(length=100), nullable=True))
    op.add_column('job_executions', sa.Column('condition_met', sa.Boolean(), nullable=True))
    op.add_column('job_executions', sa.Column('monitoring_device_mac', sa.String(length=17), nullable=True))
    op.add_column('job_executions', sa.Column('monitoring_metric', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('monitoring_device_mac', sa.String(length=17), nullable=True))
    op.add_column('jobs', sa.Column('monitoring_metric', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('operator', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('threshold_value', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('last_prometheus_value', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('last_check_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_check_time')
    op.drop_column('jobs', 'last_prometheus_value')
    op.drop_column('jobs', 'threshold_value')
    op.drop_column('jobs', 'operator')
    op.drop_column('jobs', 'monitoring_metric')
    op.drop_column('jobs', 'monitoring_device_mac')
    op.drop_column('job_executions', 'monitoring_metric')
    op.drop_column('job_executions', 'monitoring_device_mac')
    op.drop_column('job_executions', 'condition_met')
    op.drop_column('job_executions', 'prometheus_value')
    # ### end Alembic commands ###
