"""Add audit_logs table

Revision ID: f58419763463
Revises: 61f3f8c0e66c
Create Date: 2025-06-30 20:14:56.554427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58419763463'
down_revision: Union[str, None] = '61f3f8c0e66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.drop_constraint(op.f('audit_logs_platform_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'platform_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_platform_id_fkey'), 'audit_logs', 'platforms', ['platform_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###
